/*
 * Copyright (C) the libgit2 contributors. All rights reserved.
 *
 * This file is part of libgit2, distributed under the GNU GPL v2 with
 * a Linking Exception. For full terms see the included COPYING file.
 */

#ifndef INCLUDE_git_git_h__
#define INCLUDE_git_git_h__

#include "third_party/libgit2/include/git2/annotated_commit.h"
#include "third_party/libgit2/include/git2/apply.h"
#include "third_party/libgit2/include/git2/attr.h"
#include "third_party/libgit2/include/git2/blob.h"
#include "third_party/libgit2/include/git2/blame.h"
#include "third_party/libgit2/include/git2/branch.h"
#include "third_party/libgit2/include/git2/buffer.h"
#include "third_party/libgit2/include/git2/cert.h"
#include "third_party/libgit2/include/git2/checkout.h"
#include "third_party/libgit2/include/git2/cherrypick.h"
#include "third_party/libgit2/include/git2/clone.h"
#include "third_party/libgit2/include/git2/commit.h"
#include "third_party/libgit2/include/git2/common.h"
#include "third_party/libgit2/include/git2/config.h"
#include "third_party/libgit2/include/git2/credential.h"
#include "third_party/libgit2/include/git2/deprecated.h"
#include "third_party/libgit2/include/git2/describe.h"
#include "third_party/libgit2/include/git2/diff.h"
#include "third_party/libgit2/include/git2/email.h"
#include "third_party/libgit2/include/git2/errors.h"
#include "third_party/libgit2/include/git2/experimental.h"
#include "third_party/libgit2/include/git2/filter.h"
#include "third_party/libgit2/include/git2/global.h"
#include "third_party/libgit2/include/git2/graph.h"
#include "third_party/libgit2/include/git2/ignore.h"
#include "third_party/libgit2/include/git2/index.h"
#include "third_party/libgit2/include/git2/indexer.h"
#include "third_party/libgit2/include/git2/mailmap.h"
#include "third_party/libgit2/include/git2/merge.h"
#include "third_party/libgit2/include/git2/message.h"
#include "third_party/libgit2/include/git2/net.h"
#include "third_party/libgit2/include/git2/notes.h"
#include "third_party/libgit2/include/git2/object.h"
#include "third_party/libgit2/include/git2/odb.h"
#include "third_party/libgit2/include/git2/odb_backend.h"
#include "third_party/libgit2/include/git2/oid.h"
#include "third_party/libgit2/include/git2/pack.h"
#include "third_party/libgit2/include/git2/patch.h"
#include "third_party/libgit2/include/git2/pathspec.h"
#include "third_party/libgit2/include/git2/proxy.h"
#include "third_party/libgit2/include/git2/rebase.h"
#include "third_party/libgit2/include/git2/refdb.h"
#include "third_party/libgit2/include/git2/reflog.h"
#include "third_party/libgit2/include/git2/refs.h"
#include "third_party/libgit2/include/git2/refspec.h"
#include "third_party/libgit2/include/git2/remote.h"
#include "third_party/libgit2/include/git2/repository.h"
#include "third_party/libgit2/include/git2/reset.h"
#include "third_party/libgit2/include/git2/revert.h"
#include "third_party/libgit2/include/git2/revparse.h"
#include "third_party/libgit2/include/git2/revwalk.h"
#include "third_party/libgit2/include/git2/signature.h"
#include "third_party/libgit2/include/git2/stash.h"
#include "third_party/libgit2/include/git2/status.h"
#include "third_party/libgit2/include/git2/submodule.h"
#include "third_party/libgit2/include/git2/tag.h"
#include "third_party/libgit2/include/git2/transport.h"
#include "third_party/libgit2/include/git2/transaction.h"
#include "third_party/libgit2/include/git2/tree.h"
#include "third_party/libgit2/include/git2/types.h"
#include "third_party/libgit2/include/git2/version.h"
#include "third_party/libgit2/include/git2/worktree.h"

#endif
